@startuml

participant ":User" as User
participant ":ClausControl" as ClausControl
participant ":Parser" as Parser
participant ":ActionCommand" as ActionCommand
participant ":Child" as Child

User -> ClausControl: "action 1 a/helped grandma s/2"
activate ClausControl

ClausControl -> Parser: parseCommand(...)
activate Parser
Parser --> ClausControl: ActionCommand
deactivate Parser

ClausControl -> ActionCommand: execute()
activate ActionCommand

alt isFinalized
    ActionCommand --> ClausControl: "Cannot add actions after finalised!"
else not finalized
    ActionCommand -> Child: addAction("helped grandma", 2)
    activate Child
    Child --> ActionCommand
    deactivate Child
    ActionCommand --> ClausControl: "Action added for Tom..."
end

deactivate ActionCommand
ClausControl --> User: result
deactivate ClausControl

@enduml