@startuml

allowmixing
skinparam arrowThickness 1.1
skinparam arrowColor #blue

Package ClausControl <<Rectangle>>{
    Class UI
    Class Parser
    Class Storage
    Class Data
    Class Main
}

actor Santa

Santa --> UI
UI -right[#blue]-> Main
Main -[#blue]-> Parser
Parser -[#blue]-> Data
Data .[#blue]> Parser
Parser -.[#blue]> Main
Main .up.> Santa

Data -[#blue]> Storage
Storage -[#blue].> Data


@enduml