@startuml
Actor Santa
participant ":Parser" as Parser #E9F6EF
participant ":ChildCommand" as ChildCommand #E9F6EF
participant ":Name" as Name #E9F6EF
participant ":Child" as Child #E9F6EF

Santa->Parser: "child n/Bruce Wayne"
activate Parser

Parser->Parser: parseCommand("child n/Bruce Wayne")
activate Parser
Parser->Parser: prepareAdd(args)
create ChildCommand
Parser->ChildCommand: new ChildCommand("Bruce Wayne")

activate ChildCommand

create Name
ChildCommand->Name: new Name("Bruce Wayne")
activate Name
Name->Name: isValidName()
alt #f1ca9f invalid name
    Name-->ChildCommand: throwIllegalValueException
else valid name
    Name-->ChildCommand: Name object
end
deactivate Name

ChildCommand->Child: new Child(name)
activate Child
Child-->ChildCommand: Child object (toAdd)
deactivate Child
deactivate ChildCommand

ChildCommand->ChildCommand: execute()
note right: execute() adds the child to the global child list
activate ChildCommand
deactivate ChildCommand
ChildCommand --> Parser: ChildCommand

deactivate Parser
Santa<-- Parser: "Ho ho ho! New child added: Bruce Wayne"
deactivate Parser


@enduml
