@startuml
actor Santa
participant ":ClausControl" as CC
participant ":Parser" as Parser
participant ":DeliveryStatusCommand" as DSC
participant ":Child" as Child
participant ":Gift" as Gift

Santa -> CC : delivery_status CHILD_INDEX GIFT_INDEX d/delivered|d/undelivered
activate CC

CC -> Parser : parseCommand(userInput)
activate Parser
Parser -> Parser : prepareDeliverAction(args)
Parser --> CC : DeliveryStatusCommand
deactivate Parser

CC -> DSC : execute()
activate DSC

DSC -> DSC : isValidChildIndex()
DSC -> DSC : isValidGiftIndex(child)
DSC -> Child : getGifts().get(giftIndex-1)
activate Child
Child --> DSC : gift
deactivate Child

alt delivered == true
    DSC -> Gift : markDelivered()
    activate Gift
    deactivate Gift
else delivered == false
    DSC -> Gift : markUndelivered()
    activate Gift
    deactivate Gift
end

DSC --> CC : "Gift status updated! " + gift;
deactivate DSC

CC --> Santa : "Gift status updated! " + gift;
deactivate CC

@enduml