@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor Santa
participant "Parser" as Parser
participant "command :DetaskCommand" as DetaskCommand
participant "elfList" as elfList
participant "targetElf :Elf" as Elf

Santa -> Parser : "detask e/1 t/1"
activate Parser

Parser -> Parser : parseCommand("detask e/1 t/1")
create DetaskCommand
Parser -> DetaskCommand : new DetaskCommand(1, 1)

Parser -> DetaskCommand : execute()
activate DetaskCommand

opt elfIndex is invalid
    DetaskCommand --> Parser : "Error: Invalid Elf index."
else elfIndex is valid
    DetaskCommand -> elfList : get(0)
    elfList --> DetaskCommand : targetElf

    DetaskCommand -> Elf : getTasks()
    activate Elf
    Elf --> DetaskCommand : tasksArrayList
    deactivate Elf

    opt tasks is empty OR taskIndex is invalid
        DetaskCommand --> Parser : "Error: Invalid Task index."
    else taskIndex is valid
        DetaskCommand -> Elf : deleteTask(0)
        activate Elf
        Elf --> DetaskCommand
        deactivate Elf

        DetaskCommand --> Parser : "Success! Removed task..."
    end
end

deactivate DetaskCommand
Parser --> Santa : "Success! Removed task [xxx] from..."
deactivate Parser

@enduml