@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor Santa
participant ":Parser" as Parser
participant "command :EditElfCommand" as EditElfCommand
participant ":elfList" as elfList
participant "targetElf :Elf" as Elf

Santa -> Parser : "editelf 1 Buddy"
activate Parser

Parser -> Parser : parseCommand("editelf 1 Buddy")
create EditElfCommand
Parser -> EditElfCommand : new EditElfCommand(1, "Buddy")

Parser -> EditElfCommand : execute()
activate EditElfCommand

opt elfIndex is invalid
    EditElfCommand --> Parser : "Error: Invalid Elf index."
else elfIndex is valid
    EditElfCommand -> elfList : get(0)
    activate elfList
    elfList --> EditElfCommand : targetElf
    deactivate elfList

    group try [update name]
        EditElfCommand -> Elf : setName(newName)
        activate Elf
        Elf --> EditElfCommand
        deactivate Elf
        EditElfCommand --> Parser : MESSAGE_SUCCESS
    else catch IllegalValueException
        EditElfCommand --> Parser : "Error: [Exception Message]"
    end
end

deactivate EditElfCommand
Parser --> Santa : "Elf name updated!..."
deactivate Parser

@enduml
