@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor "Santa" as Santa
participant ":Parser" as Parser
participant "command:ElfCommand" as ElfCommand
participant "name:Name" as Name
participant "toAdd:Elf" as Elf
participant "elfList" as elfList

Santa -> Parser : "elf Buddy"
activate Parser

Parser -> Parser : parseCommand("elf Buddy")

create ElfCommand
Parser -> ElfCommand : new ElfCommand("Buddy")
activate ElfCommand

create Name
ElfCommand -> Name : new Name("Buddy")
activate Name
Name -> Name : isValidName()

opt invalid name
    Name --> ElfCommand : throwIllegalValueException
    deactivate Name
else valid name
    Name --> ElfCommand : Name object
    deactivate Name
end

create Elf
ElfCommand -> Elf :new Elf(name)
activate Elf
Elf --> ElfCommand : Elf object (toAdd)
deactivate Elf

Parser -> ElfCommand : execute()
ElfCommand -> elfList : add(toAdd)
activate elfList
elfList --> ElfCommand
deactivate elfList

ElfCommand --> Parser : MESSAGE_SUCCESS
deactivate ElfCommand

Parser --> Santa : "Ho ho ho! New elf added: Buddy"
deactivate Parser

@enduml