@startuml
skinparam dpi 600

participant User
participant ClausControl
participant Parser
participant FinalizeCommand
participant ActionCommand

User -> ClausControl: "finalize"
activate ClausControl

ClausControl -> Parser: parseCommand("finalize")
activate Parser
Parser --> ClausControl: FinalizeCommand
deactivate Parser

ClausControl -> FinalizeCommand: execute()
activate FinalizeCommand
FinalizeCommand --> ClausControl: "Lists have been finalised!"
deactivate FinalizeCommand

note over ClausControl : isFinalized = true

ClausControl --> User: "Lists have been finalised!"
deactivate ClausControl

User -> ClausControl: "action 1 a/test s/2"
activate ClausControl

ClausControl -> Parser: parseCommand(...)
activate Parser
Parser --> ClausControl: ActionCommand
deactivate Parser

ClausControl -> ActionCommand: execute()
activate ActionCommand
ActionCommand --> ClausControl: "Cannot add actions after finalised!"
deactivate ActionCommand

ClausControl --> User: "Cannot add actions after finalised!"
deactivate ClausControl

@enduml