@startuml
actor Santa
participant ":ClausControl" as CC
participant ":Parser" as Parser
participant ":PrepareGiftCommand" as PGC
participant ":Child" as Child
participant ":Gift" as Gift

Santa -> CC : prepared CHILD_INDEX GIFT_INDEX
activate CC

CC -> Parser : parseCommand(userInput)
activate Parser
Parser -> Parser : preparePreparedAction(args)
Parser --> CC : PrepareGiftCommand
deactivate Parser

CC -> PGC : execute()
activate PGC

PGC -> PGC : isValidChildIndex()
PGC -> PGC : isValidGiftIndex(child)
PGC -> Child : getGifts().get(giftIndex-1)
activate Child
Child --> PGC : gift
deactivate Child

PGC -> Gift : markPrepared()
activate Gift
deactivate Gift

PGC --> CC : "Gift marked as prepared!!!"
deactivate PGC

CC --> Santa : result
deactivate CC

@enduml