@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor "Santa" as Santa
participant ":Parser" as Parser
participant "command:ResetCommand" as ResetCommand
participant "childList:ChildList" as childList
participant "elfList:ElfList" as elfList

Santa -> Parser : "reset"
activate Parser

Parser -> Parser : parseCommand("reset")

create ResetCommand
Parser -> ResetCommand : <<create>>\nnew ResetCommand()
activate ResetCommand

Parser -> ResetCommand : execute()

note over ResetCommand : isFinalized = false

ResetCommand -> childList : clear()
activate childList
childList --> ResetCommand
deactivate childList

ResetCommand -> elfList : clear()
activate elfList
elfList --> ResetCommand
deactivate elfList

ResetCommand --> Parser : MESSAGE_SUCCESS
deactivate ResetCommand

Parser --> Santa : "Ho ho ho! The system has been fully reset."
deactivate Parser

@enduml