@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor "Santa" as Santa
participant ":Parser" as Parser
participant "command:RmElfCommand" as RmElfCommand
participant "elfList:ElfList" as elfList

Santa -> Parser : "rmelf 1"
activate Parser

Parser -> Parser : parseCommand("rmelf 1")

create RmElfCommand
Parser -> RmElfCommand : <<create>>\nnew RmElfCommand(1)
activate RmElfCommand

Parser -> RmElfCommand : execute()

RmElfCommand -> elfList : size()
activate elfList
elfList --> RmElfCommand : listSize
deactivate elfList

opt elfIndex is invalid
    RmElfCommand --> Parser : throw CommandException
else elfIndex is valid
    RmElfCommand -> elfList : get(0)
    activate elfList
    elfList --> RmElfCommand : removedElf
    deactivate elfList
    RmElfCommand -> elfList : remove(0)
    activate elfList
    elfList --> RmElfCommand
    deactivate elfList

    RmElfCommand --> Parser : MESSAGE_SUCCESS
end

deactivate RmElfCommand

Parser --> Santa : "Ho ho ho! Elf removed: Buddy"
deactivate Parser

@enduml