@startuml
participant ":ClausControl" as App
participant ":Storage" as Storage
participant ":Child" as Child
participant ":Gift" as Gift
participant ":Elf" as Elf

App -> Storage : load()
activate Storage

loop while (readLine != null)
    Storage -> Storage : readLine()

    alt parts[0] == "CHILD"
        Storage -> Child : new Child(Name(name), age, location,naughty/nice)
        activate Child
        Child --> Storage
        deactivate Child
        Storage -> Storage : children.add(currentChild)
        note right
            currentChild = Child
            currentElf = null
        end note

    else parts[0] == "FINALIZED"
        Storage -> Storage : isFinalized = Boolean.parseBoolean(parts[1])

    else parts[0] == "GIFT"
        Storage -> Gift : new Gift(giftName)
        activate Gift
        Gift --> Storage
        alt state == PREPARED
            Storage -> Gift : markPrepared()
            Gift --> Storage
        else state == DELIVERED
            Storage -> Gift : markDelivered()
            Gift --> Storage
        end
        deactivate Gift
        Storage -> Child : addGift(gift)
        activate Child
        Child --> Storage
        deactivate Child

    else parts[0] == "ACTION"
        Storage -> Child : addAction(action, severity)
        activate Child
        Child --> Storage
        deactivate Child

    else parts[0] == "ELF"
        Storage -> Elf : new Elf(Name(parts[1]))
        activate Elf
        Elf --> Storage
        deactivate Elf
        Storage -> Storage : elves.add(currentElf)
        note right
            currentElf = Elf
            currentChild = null
        end note

    else parts[0] == "TASK"
        Storage -> Elf : addTask(new ElfTask(parts[1]))
        activate Elf
        Elf --> Storage
        deactivate Elf

    end
end

Storage --> App : StorageData(children, elves, isFinalized)
deactivate Storage

@enduml