@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor "Santa" as Santa
participant ":Parser" as Parser
participant "command:TaskCommand" as TaskCommand
participant "elfList:ElfList" as elfList
participant "targetElf:Elf" as Elf
participant "newTask:ElfTask" as ElfTask

Santa -> Parser : "task 1 t/Make toys"
activate Parser

Parser -> Parser : parseCommand("task 1 t/Make toys")

create TaskCommand
Parser -> TaskCommand : new TaskCommand(1, "Make toys")
activate TaskCommand

Parser -> TaskCommand : execute()

TaskCommand -> elfList : size()
activate elfList
elfList --> TaskCommand : listSize
deactivate elfList

opt targetIndex is invalid
    TaskCommand --> Parser : MESSAGE_INVALID_INDEX
else targetIndex is valid
    TaskCommand -> elfList : get(0)
    activate elfList
    elfList --> TaskCommand : targetElf
    deactivate elfList

    create ElfTask
    TaskCommand -> ElfTask : new ElfTask("Make toys")
    activate ElfTask
    ElfTask --> TaskCommand : newTask
    deactivate ElfTask

    TaskCommand -> Elf : addTask(newTask)
    activate Elf
    Elf --> TaskCommand
    deactivate Elf

    TaskCommand --> Parser : MESSAGE_SUCCESS
end

deactivate TaskCommand
Parser --> Santa : "Ho ho ho! Task [Make toys] assigned..."
deactivate Parser

@enduml