package seedu.duke;

import seedu.duke.commands.Command;
import seedu.duke.data.child.Child;
import seedu.duke.data.elf.Elf;
import seedu.duke.data.exception.IllegalValueException;
import seedu.duke.parser.Parser;
import seedu.duke.ui.TextUi;

import seedu.duke.storage.Storage;
import java.io.IOException;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import seedu.duke.commands.FinalizeCommand;


//@@author shrabasti-c
// Solution below adapted from https://github.com/se-edu/addressbook-level2/blob
// /master/src/seedu/addressbook/Main.java
// with minor modifications
public class Duke {
    public static final String LOGO = "  .-\"\"-.\n" +
            " /,..___\\\n" +
            "() {_____}\n" +
            "  (/-@-@-\\)\n" +
            "  {`-=^=-'}\n" +
            "  {  `-'  } Welcome to ClausControl, Santa!\n" +
            "   {     }\n" +
            "    `---'\n";

    private static Logger logger = Logger.getLogger("Foo");
    private TextUi ui = new TextUi();
    private final Parser parser = new Parser();
    private ArrayList<Child> childList = new ArrayList<>();
    private ArrayList<Elf> elfList = new ArrayList<>();

    private Storage storage= new Storage("data.txt");

    //@@author GShubhan
    private boolean isFinalized = false;
    //@@author

    //@@author shrabasti-c-reused
    //this function was generated by Claude
    public Duke() {
        this(System.in);
    }

    //this function was generated by Claude
    public Duke(InputStream inputStream) {
        this.ui = new TextUi(inputStream);
        //@@author prerana-r11
        try {
            this.childList = new ArrayList<>(storage.load());
        } catch (IOException e) {
            this.childList = new ArrayList<>();
        }
        //@@author

    }
    //@@author

    /** Reads the user command and executes it, until the user issues the exit command.  */
    private void runCommandLoopUntilExitCommand() throws IllegalValueException {
        Command command;
        do {
            try {
                String userCommandText = ui.getUserCommand();
                if (userCommandText.equals("bye")) {
                    logger.log(Level.INFO, "end of processing");
                    return;
                }
                command = parser.parseCommand(userCommandText);
                command.setData(childList, elfList, isFinalized);
                //@@author GShubhan
                String result = command.execute();
                try {
                    storage.save(childList);
                } catch (IOException e) {
                    logger.warning("Error saving: " + e.getMessage());
                }
                if (command instanceof FinalizeCommand) {
                    isFinalized = true;
                }
                System.out.println(result); //TODO: ui formatting required
                //@@author
            } catch (IllegalValueException e) {
                System.out.println(e.getMessage()); //TODO: ui formatting required
                logger.log(Level.INFO, "processing error");
            } catch(Exception e){
                return;
            }
        } while (true);
    }

    /** Runs the program until termination.  */
    public void run() throws IllegalValueException {
        System.out.println(LOGO);
        runCommandLoopUntilExitCommand();
        //System.exit(0);
    }

    /**
     * Main entry-point for the ClausControl application.
     */
    public static void main(String[] args) throws IllegalValueException {
        Logger.getLogger("seedu.duke").setLevel(Level.WARNING);
        new Duke().run();
    }
}
//@@author

