//Solution below adapted from https://github.com/se-edu/addressbook-level2/blob
// /master/src/seedu/addressbook/Main.java
// with minor modifications
package seedu.duke;

import seedu.duke.commands.Command;
import seedu.duke.data.child.Child;
import seedu.duke.data.exception.IllegalValueException;
import seedu.duke.parser.Parser;
import seedu.duke.ui.TextUi;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Duke {
    public static final String LOGO = "  .-\"\"-.\n" +
            " /,..___\\\n" +
            "() {_____}\n" +
            "  (/-@-@-\\)\n" +
            "  {`-=^=-'}\n" +
            "  {  `-'  } Welcome to ClausControl, Santa!\n" +
            "   {     }\n" +
            "    `---'\n";

    private TextUi ui = new TextUi();
    private final Parser parser = new Parser();
    private ArrayList<Child> childList = new ArrayList<>();

    private static Logger logger = Logger.getLogger("Foo");

    //this function was generated by Claude
    public Duke() {
        this(System.in);
    }

    //this function was generated by Claude
    public Duke(InputStream inputStream) {
        this.ui = new TextUi(inputStream);
    }

    /** Reads the user command and executes it, until the user issues the exit command.  */
    private void runCommandLoopUntilExitCommand() throws IllegalValueException {
        Command command;
        do {
            try {
                String userCommandText = ui.getUserCommand();
                if (userCommandText.equals("bye")) {
                    logger.log(Level.INFO, "end of processing");
                    return;
                }
                command = parser.parseCommand(userCommandText);
                command.setData(childList);
                String result = command.execute();
                System.out.println(result); //TODO: ui formatting required
            } catch (IllegalValueException e) {
                System.out.println(e.getMessage()); //TODO: ui formatting required
                logger.log(Level.INFO, "processing error");
            }
        } while (true);
    }

    /** Runs the program until termination.  */
    public void run() throws IllegalValueException {
        System.out.println(LOGO);
        runCommandLoopUntilExitCommand();
        //System.exit(0);
    }

    /**
     * Main entry-point for the ClausControl application.
     */
    public static void main(String[] args) throws IllegalValueException {
        new Duke().run();
    }
}

